{
  "hash": "74b85b65cf2440f3bd93a1b51ba9d939",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 'Network Models: Evaluating the resilience of the London Underground Network'\ndescription: |\n  An application of network science to evaluate the resilience of the London Underground network\nauthor: Benjamin Tee\ndate: '2026-04-26'\nbibliography: References.bib\nnocite: |\n  @*\ncsl: harvard-cite-them-right.csl\ncategories:\n  - Networks\n  - Urban Simulation\n  - Resilience\n  - Complexity\nimage: London-underground-map.png\nimage-alt: 'Network Models: Evaluating the resilience of the London Underground Network'\ndraft: false\n---\n\n## 1. Objective\n\nThis analysis applies concepts in network science to evaluate the resilience of the London Underground. We examine the differences when we look at the network topologically and when weighted by observed passenger flows. The study then rounds off by simulating station closures, to identify which stations have the most significant impact on the network. \n\n## 2. Background\n\nNetwork science began with a puzzle about a city. In 1736, Leonhard Euler was asked whether one could cross all seven bridges of the Königsberg exactly once. His answer, that this depended not on the bridges' lengths or the city's layout, but on how the landmasses connected, established a founding insight of graph theory:  structure alone determines what a system permits [@hopkins_early_2009].\n\nThe method is surprisingly simple. Represent a system as **nodes** joined by **edges**, and much of its behaviour becomes calculable. For a transit network, the translation is natural: stations are nodes, track between them edges. This gives a **topological network**, a map of connectivity, indifferent to distance or demand, which isolates what the system's shape alone implies about where it is fragile.\n\nBut structure is only half the story. A station may sit at a critical junction and carry almost nobody while another may lie on an unremarkable stretch of line and move tens of thousands each morning. Attaching passenger volumes to edges produces a **weighted network**, shifting the question from how a system is built to how it is actually used. \n\nResilience can be further understood through the concept of **centrality** which asks the question \"which nodes matter most\". Depending on the objective, a station might be important because many lines meet there, because a disproportionate share of journeys must route through it, or because it sits close to everywhere else. \n\n## 3. Network Centrality Measures\n\nCentrality measures [@newman_measures_2010] can be computed for the underground network as follows: \n\n1.  **Degree Centrality** counts the number of direct connections a node has, reflecting its immediate prominence in the network. For a node v in graph G with N nodes, it can be represented as:\n\n    $$\n    C_D(v) = \\frac{deg(v)}{N-1}\n    $$\n\n    where $deg(v)$ is the number of edges that are incident to $v$ and the denominator normalises by the maximum possible degree. **Degree centrality** identifies underground stations with the most number of direct line connections such as interchanges (e.g. King's Cross St. Pancras station with six lines). High degree nodes are critical because they are the primary points of passenger transfer between lines. When a high-degree station fails, passengers lose multiple routing options.\n\n2.  **Betweenness Centrality** measures how frequently a node lies on the shortest path between other node pairs. It can be represented as\n\n    $$\n    x_i = \\sum_{s \\neq i \\neq t} \\frac{\\sigma_{st}(i)}{\\sigma_{st}}\n    $$\n\n    where $\\sigma_{st}$ is the total number of shortest paths between nodes $s$ and $t$, $\\sigma_{st}(i)$ is the number of those paths passing through node $i$, and the condition $s \\neq i \\neq t$ indicates that $i$ is an intermediate node rather than an endpoint. **Betweenness centrality** identifies stations that act as 'bridges' or 'brokers' in the underground network where a disproportionate share of journeys must pass through to find the shortest route. They sit at structurally pivotal positions in the network geography and bridge between two otherwise weakly connected clusters. High betweenness centrality nodes are critical because their removal would force many passengers onto less efficient alternative routes or eliminate viable routes altogether.\n\n3.  **Closeness Centrality** measures how close a node is to all other nodes in the network, based on the sum of shortest path distances. It can be represented as:\n\n    $$\n    C_i = \\frac {1}{l_i} = \\frac {n}{\\sum_j d_{ij}} \n    $$\n\n    where $d_{ij}$ us the length of a geodesic path from $i$ to $j$ and $l_i$ is the mean geodesic distance from $i$ to $j$, averaged over all vertices in the network. **Closeness centrality** identifies underground stations from which the entire network is most efficiently reachable which minimise expected travel time or transfers to any destination. From a resilience perspective, high closeness stations are crucial because their failure degrades network-wide accessibility most severely. When a high-closeness station closes, average journey lengths across the entire network increase substantially.\n\n![Figure 1: A quick visual of centrality measures](figures/centrality_measures.png){fig-alt=\"A quick visual of centrality measures\"}\n\n## 4.1 Topological Network \n\nThe topological measure of the network reflects the infrastructural view of the network with stations as nodes and connecting lines as unweighted edges. While this allows us to identify structurally important stations based on network position, it may abstracts away information (e.g. distance, passenger flows) that could matter more.\n\n\n\n\n\n\n\n::: {#tbl-centrality .cell tbl-cap='Top 10 stations by degree, betweenness, and closeness centrality (topological network)' execution_count=4}\n|     | Degree Centrality        |      | Betweenness Centrality   |       | Closeness Centrality     |\n|----:|:-------------------------|-----:|:-------------------------|------:|:-------------------------|\n|   1 | Stratford                |    1 | Stratford                |     1 | Green Park               |\n|   2 | Bank and Monument        |    2 | Bank and Monument        |     2 | Bank and Monument        |\n|   3 | King's Cross St. Pancras |    3 | Liverpool Street         |     3 | King's Cross St. Pancras |\n|   4 | Baker Street             |    4 | King's Cross St. Pancras |     4 | Westminster              |\n|   5 | Green Park               |    5 | Waterloo                 |     5 | Waterloo                 |\n|   6 | Liverpool Street         |    6 | Green Park               |     6 | Oxford Circus            |\n|   7 | Oxford Circus            |    7 | Euston                   |     7 | Bond Street              |\n|   8 | Waterloo                 |    8 | Westminster              |     8 | Angel                    |\n|   9 | West Ham                 |    9 | Baker Street             |     9 | Farringdon               |\n|  10 | Earl's Court             |   10 | Finchley Road            |    10 | Moorgate                 |\n:::\n\n\n## 4.2 Scenario Analysis - Topological node removal \n\nTo investigate the resilience of the topological network, we sequentially remove the highest ranked node (by each centrality measure) and evaluate the impact on the (a) number of connected components, (b) largest connected component, (c) diameter of the largest connected component. \n\n| Metric | What it measures | What a change signals |\n|---|---|---|\n| **Number of connected components** | How many separate sub-networks the system has fractured into. A value of 1 means every station remains reachable from every other. | An increase means the network has broken apart: some stations can no longer be reached from others by tube at all. |\n| **Size of the largest connected component (LCC)** | The number of stations in the biggest remaining intact sub-network. | A sharp fall means the removal has severed a substantial portion of the network, not merely trimmed its edges. |\n| **Diameter of the largest connected component** | The longest shortest path within that sub-network — the number of stops between its two most distant stations. | An increase means journeys have become less direct: the network still holds together, but passengers must travel further to cross it. |\n\n: Structural metrics used to assess network degradation under sequential node removal {#tbl-resilience-metrics}\n\n\n\n|   Iteration | Node Removed             |   LCC Size |   No. of Components |   Diameter of LCC |\n|------------:|:-------------------------|-----------:|--------------------:|------------------:|\n|           0 | —                        |        401 |                   1 |                36 |\n|           1 | Stratford                |        379 |                   3 |                49 |\n|           2 | Bank and Monument        |        378 |                   3 |                49 |\n|           3 | King's Cross St. Pancras |        377 |                   3 |                49 |\n|           4 | Baker Street             |        374 |                   4 |                49 |\n|           5 | Canning Town             |        360 |                   6 |                50 |\n|           6 | Green Park               |        359 |                   6 |                51 |\n|           7 | Earl's Court             |        358 |                   6 |                51 |\n|           8 | Waterloo                 |        357 |                   6 |                51 |\n|           9 | Turnham Green            |        356 |                   6 |                53 |\n|          10 | Willesden Junction       |        337 |                   8 |                59 |\n\n: Sequential node removal ranked by degree centrality {#tbl-removal-degree}\n\n\n|   Iteration | Node Removed             |   LCC Size |   No. of Components |   Diameter of LCC |\n|------------:|:-------------------------|-----------:|--------------------:|------------------:|\n|           0 | —                        |        401 |                   1 |                36 |\n|           1 | Stratford                |        379 |                   3 |                49 |\n|           2 | King's Cross St. Pancras |        378 |                   3 |                49 |\n|           3 | Waterloo                 |        377 |                   3 |                49 |\n|           4 | Bank and Monument        |        376 |                   3 |                49 |\n|           5 | Canada Water             |        375 |                   3 |                55 |\n|           6 | West Hampstead           |        227 |                   4 |                38 |\n|           7 | Earl's Court             |        226 |                   4 |                39 |\n|           8 | Shepherd's Bush          |        196 |                   5 |                37 |\n|           9 | Euston                   |        173 |                   6 |                38 |\n|          10 | Baker Street             |        170 |                   7 |                48 |\n\n: Sequential node removal ranked by betweenness centrality {#tbl-removal-betweenness}\n\n\n|   Iteration | Node Removed             |   LCC Size |   No. of Components |   Diameter of LCC |\n|------------:|:-------------------------|-----------:|--------------------:|------------------:|\n|           0 | —                        |        401 |                   1 |                36 |\n|           1 | Green Park               |        400 |                   1 |                36 |\n|           2 | King's Cross St. Pancras |        399 |                   1 |                38 |\n|           3 | Waterloo                 |        398 |                   1 |                40 |\n|           4 | Bank and Monument        |        397 |                   1 |                42 |\n|           5 | West Hampstead           |        396 |                   1 |                50 |\n|           6 | Canada Water             |        226 |                   2 |                38 |\n|           7 | Stratford                |        226 |                   4 |                38 |\n|           8 | Earl's Court             |        225 |                   4 |                39 |\n|           9 | Shepherd's Bush          |        195 |                   5 |                40 |\n|          10 | Oxford Circus            |        194 |                   5 |                40 |\n\n: Sequential node removal ranked by closeness centrality {#tbl-removal-closeness}\n\n\n\n\n::: {#cell-fig-node-removal .cell execution_count=7}\n\n::: {.cell-output .cell-output-display}\n![Network degradation under sequential node removal, by centrality measure. Each removal targets the highest-ranked remaining node, with centrality recomputed after every step.](index_files/figure-html/fig-node-removal-output-1.png){#fig-node-removal width=1239 height=489}\n:::\n:::\n\n\nThe results reveal differences in how each measure identifies vulnerable stations and the severity of degradation following removal.\n\n**Degree centrality** targets the most connected interchange stations. Its effect on the largest component is gradual (337 stations retained after 10 removals), but it fragments the network more than either alternative, producing 8 separate components and stretching the surviving diameter furthest, from 36 to 59 stops. Removing well-connected hubs shears off peripheral branches without severing the core.\n\n**Betweenness centrality** identifies broker stations lying on the greatest number of shortest paths. Early removals produce similar degradation to degree, but removing West Hampstead at iteration 6 cuts the LCC from 375 to 227 stations in a single step. The accompanying fall in diameter, from 55 to 38, is not an improvement: the network has shed its longest branches into separate fragments rather than becoming more compact. Broker stations are distinctive because they act as sole connectors between otherwise separate segments, so their failure causes disproportionate connectivity loss.\n\n**Closeness centrality** targets stations that anchor overall network efficiency. Its first five removals leave the network entirely intact, with the diameter expanding steadily from 36 to 50 stops. Removing Canada Water at iteration 6 then collapses the LCC from 396 to 226 stations, showing that a network can absorb sustained degradation before failing abruptly.\n\nThese distinctions carry direct policy implications. *High-betweenness stations* (King's Cross, West Hampstead, Euston) represent structural failure risks requiring contingency planning and route redundancy. *High-closeness stations* (Green Park, Waterloo, Bank and Monument) anchor system-wide efficiency, and their disruption warrants demand-management strategies even where connectivity remains intact. *Betweenness centrality* is the most operationally useful single measure for identifying catastrophic failure points, but it should be monitored alongside *closeness centrality*, which captures the slower degradation in journey times that fragmentation metrics miss entirely.\n\n## 5.1 Weighted Network (Flows)\n\n\n\n::: {#tbl-centrality-weighted .cell tbl-cap='Top 10 stations by weighted degree, betweenness, and closeness centrality (flow-weighted network). Betweenness and closeness use inverse flows as edge weights, so heavily used corridors are treated as shorter paths.' execution_count=9}\n|     | Weighted Degree          |      | Weighted Betweenness   |       | Weighted Closeness   |\n|----:|:-------------------------|-----:|:-----------------------|------:|:---------------------|\n|   1 | Bank and Monument        |    1 | Green Park             |     1 | Green Park           |\n|   2 | Green Park               |    2 | Bank and Monument      |     2 | Westminster          |\n|   3 | Waterloo                 |    3 | Waterloo               |     3 | Waterloo             |\n|   4 | King's Cross St. Pancras |    4 | Westminster            |     4 | Bank and Monument    |\n|   5 | Westminster              |    5 | Liverpool Street       |     5 | Oxford Circus        |\n|   6 | Liverpool Street         |    6 | Stratford              |     6 | Victoria             |\n|   7 | Euston                   |    7 | Euston                 |     7 | Bond Street          |\n|   8 | Stratford                |    8 | Victoria               |     8 | Liverpool Street     |\n|   9 | Victoria                 |    9 | Oxford Circus          |     9 | Warren Street        |\n|  10 | Baker Street             |   10 | Bond Street            |    10 | Stratford            |\n:::\n\n\nAttaching flows changes the picture substantially. Under **weighted degree centrality**, [**Bank & Monument**]{.underline} (646,117) has the largest connection strength in passenger terms — a station's importance now reflects how many people pass through it rather than how many lines meet there.\n\nThe shift is sharper for **weighted betweenness**, where [**Green Park**]{.underline} (45,000) emerges as the most critical broker, followed by *Bank and Monument* (36,249) and *Waterloo* (31,444). *Stratford*, which topped the topological betweenness ranking, falls to sixth. *Green Park's* rise makes operational sense: it sits at the intersection of the Jubilee, Victoria and Piccadilly lines, bridging three of the highest-flow corridors in central London. The weighted ranking concentrates almost entirely on Zone 1, reflecting that the most operationally significant brokers are those bridging the highest-demand corridors, not those that happen to lie on topological shortest paths.\n\nUnder **weighted closeness**, [**Green Park**]{.underline} ranks first (95.98), with *Westminster*, *Waterloo* and *Bank and Monument* close behind. The scores are, however, tightly clustered. The top ten span less than 0.1%, which suggests both a well-connected Zone 1 core and that inverse-flow weighting compresses the distance scale enough to limit the measure's discriminating power.\n\n## 5.2 Scenario Analysis - Closure of Origin Station\n\n*Station-pair with largest Origin-Destination (OD) Flow* \n\n\n\nThe largest single origin–destination flow runs from **Waterloo** to\n**Bank and Monument**, carrying 15\\,946 passengers during\nthe AM peak.  This reflects the intense commuter demand between the South Bank and the City of London during morning rush hour.\n\nClosing Waterloo would affect  \n- **90\\,722** passengers in total  \n- **67\\,314** departing and  \n- **23\\,408** arriving.  \n\nThese figures reflect AM Peak demand only (NUMBAT timeband 3), and are most applicable to peak commuter conditions. Waterloo's role as a major South Bank terminus means its AM Peak outflows are particularly high relative to other periods. It should be noted that the OD flows represent direct station-to-station demand from the NUMBAT dataset [@tfl_2025], distinct from the edge-level flow weights used in the weighted centrality analysis in Section 2.1, which were derived by assigning all OD demand onto shortest paths through the network.\n\n::: {#tbl-top-od .cell tbl-cap='Top 10 origin–destination pairs by passenger flow (AM peak, Monday–Thursday)' execution_count=11}\n|   Rank | Origin           | Destination          | Passengers   |\n|-------:|:-----------------|:---------------------|:-------------|\n|      1 | Waterloo         | Bank and Monument    | 15,946       |\n|      2 | Waterloo         | Canary Wharf         | 8,085        |\n|      3 | Stratford        | Liverpool Street     | 6,946        |\n|      4 | London Bridge    | Canary Wharf         | 6,165        |\n|      5 | Victoria         | Oxford Circus        | 5,181        |\n|      6 | Canada Water     | Canary Wharf         | 4,030        |\n|      7 | Stratford        | Canary Wharf         | 3,875        |\n|      8 | Liverpool Street | Farringdon           | 3,755        |\n|      9 | Finsbury Park    | Highbury & Islington | 3,659        |\n|     10 | Canada Water     | London Bridge        | 3,202        |\n:::\n\n\n*Routing options for closure of origin station*\n\nIf the origin station were closed, which station should passengers go to instead, and how long would it take them to walk there? These are questions network analysis can answer directly.\n\nCandidate stations were first identified within 1,500 m Euclidean distance of the affected station.\n\n\n\n::: {#tbl-candidates .cell tbl-cap='Stations within 1,500 m straight-line distance of Waterloo' execution_count=13}\n|   Rank | Station           | Straight-line distance (m)   |\n|-------:|:------------------|:-----------------------------|\n|      1 | Lambeth North     | 486                          |\n|      2 | Southwark         | 649                          |\n|      3 | Embankment        | 721                          |\n|      4 | Westminster       | 841                          |\n|      5 | Temple            | 891                          |\n|      6 | Charing Cross     | 1,021                        |\n|      7 | Blackfriars       | 1,244                        |\n|      8 | Elephant & Castle | 1,284                        |\n|      9 | Covent Garden     | 1,306                        |\n|     10 | Leicester Square  | 1,337                        |\n|     11 | St. James's Park  | 1,386                        |\n|     12 | Borough           | 1,471                        |\n:::\n\n\nFor each candidate, walking distance from Waterloo was computed as the shortest path on the OSMnx pedestrian road network. Assuming a walking speed of 1.3 m/s [@TfL_planning_2020], this yields a walking time. Tube travel time was then added, based on the shortest path through the Underground network to the destination station. Two rankings follow: the closest station on foot, and the fastest overall journey.\n\n::: {#tbl-best-total .cell tbl-cap='Alternative stations ranked by shortest total travel time' execution_count=14}\n|   Rank | Alternative station   |   Walking time (min) |   Walking dist (m) |   Tube time (min) |   Total travel time (min) |\n|-------:|:----------------------|---------------------:|-------------------:|------------------:|--------------------------:|\n|      1 | Southwark             |                 11.2 |                873 |               3.3 |                      14.5 |\n|      2 | Embankment            |                 12.4 |                965 |               4.6 |                      17.0 |\n|      3 | Lambeth North         |                 11.9 |                931 |               5.2 |                      17.1 |\n|      4 | Temple                |                 17.8 |              1,390 |               3.3 |                      21.1 |\n|      5 | Westminster           |                 16.0 |              1,251 |               5.7 |                      21.7 |\n|      6 | Blackfriars           |                 19.8 |              1,544 |               2.1 |                      21.9 |\n|      7 | Charing Cross         |                 16.8 |              1,314 |               5.2 |                      22.0 |\n|      8 | Elephant & Castle     |                 19.0 |              1,483 |               3.7 |                      22.7 |\n|      9 | Borough               |                 22.4 |              1,746 |               2.3 |                      24.7 |\n|     10 | Covent Garden         |                 20.7 |              1,613 |               5.2 |                      25.9 |\n|     11 | Leicester Square      |                 21.7 |              1,695 |               5.8 |                      27.5 |\n|     12 | St. James's Park      |                 25.3 |              1,975 |               6.6 |                      31.9 |\n:::\n\n\nThe fastest alternative journey runs through **Southwark** at\n14\\.5 minutes.\n\nWalking times across all candidates range from\n11\\.2 to\n25\\.3 minutes, so the burden of disruption falls unevenly depending on where within the station's catchment a passenger begins.\n\n::: {#cell-fig-alternatives .cell .column-page execution_count=15}\n\n::: {.cell-output .cell-output-display}\n![Alternative boarding stations following Waterloo closure. Candidates lie within 1,800 m straight-line distance of the closed station, with walking routes computed on the OSMnx pedestrian network and journey times to Bank and Monument. The three fastest options by total travel time are highlighted; the second and third are effectively tied given the model's flat tube-speed assumption.](index_files/figure-html/fig-alternatives-output-1.png){#fig-alternatives width=1334 height=839}\n:::\n:::\n\n\n## 6. Reflections and Limitations\n\nRepresenting stations as nodes and the links between adjacent stations as edges is a simple but powerful concept. This enables the computation of network centrality measures that assess whuch stations carry most structural weight. The sequential removal of nodes reveals how much the network can lose before it fractures. Shortest-path algorithms show which viable alternatives are most efficient when a station closes. \n\nFindings depend on whether a topological or weighted network view is adoppted. Stratford leads the topological rankings but falls to sixth once passenger flows are attached, while Green Park rises to first. Neither is wrong, they just describe different kinds of importance. A station can be structurally pivotal while carrying modest demand, or the reverse. For planning, that means taking into account both views when deploying resilience enhancement measures. \n\nSome simplifications are worth noting. This model treats travel time as proportional to distance, setting aside dwell time at stations, service frequency and the cost of changing lines — which matters most where alternatives are separated by a minute or two. The removal experiment also assumes displaced passengers disappear, when in practice they redistribute onto neighbouring stations. Coupling the network structure to a demand-assignment model would capture that cascade, and would be a natural next step for further analysis.\n\n*This article was partially drawn from my coursework for the CASA0002 Urban Simulation assignment.*   \n*Source code and data can be found [here](https://github.com/benjamintee/CASA_UrbSIM_Assessment).* \n\n## References\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}